### ISSUE TITLE
Provide delighters.js via npm

### ISSUE THREAD

**Issue by goloroden** [Q42/delighters#2]
Hey there 😊 

First of all: great work, delighters.js is a really nice and very useful library!
Thanks for this!

AFAICS you currently need to download the script and add a `<script>` tag to your site, which is fine for very simple or legacy applications, but doesn't feel right in a modern environment using webpack or something similar.

Would it be possible to provide the module via npm, so that one can install it as a regular dependency? This would be great 👍

**Comment by jayeshanandani** [comment]
Please provide it via `npm`. It will be a great add-on to be part of automation script.

**Comment by champi-dev** [comment]
Has anyone already forked this repo and published it on npm?

I ended up using https://github.com/xtianmiller/emergence.js
